[2022-11-30 14:27:35,645] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:28:40,569] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:32:17,332] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:35:55,297] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:45:23,319] WARNING in _internal:  * Debugger is active!
[2022-11-30 14:49:00,401] WARNING in _internal:  * Debugger is active!
[2022-11-30 15:03:24,590] WARNING in _internal:  * Debugger is active!
[2022-11-30 15:07:34,299] WARNING in _internal:  * Debugger is active!
[2022-11-30 16:08:07,181] WARNING in _internal:  * Debugger is active!
[2022-11-30 15:13:01,365] ERROR in app: Exception on /user/shopping-bag [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/grey/WebProject/team_2web/blueprint/user_blueprint.py", line 211, in shopping_bag
    for order in user.shoppingList[0].orders:
AttributeError: 'NoneType' object has no attribute 'shoppingList'
[2022-11-30 15:54:09,774] ERROR in app: Exception on /search/ [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/grey/WebProject/team_2web/app.py", line 110, in search
    return render_template("search_result.html", page_data=page_data, keywords=keyword, searchForm=search_form)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/grey/WebProject/team_2web/templates/search_result.html", line 41, in template
    {% block jsLink %
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '%'
[2022-11-30 15:54:30,825] ERROR in app: Exception on /search/ [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/grey/WebProject/team_2web/app.py", line 110, in search
    return render_template("search_result.html", page_data=page_data, keywords=keyword, searchForm=search_form)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/grey/WebProject/team_2web/templates/search_result.html", line 41, in template
    {% block jsLink %
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '%'
[2022-11-30 17:28:23,052] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:28:26,071] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:32:52,083] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:34:58,537] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:35:21,947] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:36:28,637] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:38:09,014] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:50:02,111] WARNING in _internal:  * Debugger is active!
[2022-11-30 17:51:45,573] WARNING in _internal:  * Debugger is active!
[2022-12-01 23:20:32,671] WARNING in _internal:  * Debugger is active!
[2022-12-02 00:03:14,760] WARNING in _internal:  * Debugger is active!
[2022-12-02 00:05:56,182] WARNING in _internal:  * Debugger is active!
[2022-12-02 00:11:13,314] WARNING in _internal:  * Debugger is active!
[2022-12-02 00:24:00,180] WARNING in _internal:  * Debugger is active!
[2022-12-02 00:28:21,565] WARNING in _internal:  * Debugger is active!
[2022-12-02 08:24:43,843] WARNING in _internal:  * Debugger is active!
[2022-12-02 08:53:54,550] WARNING in _internal:  * Debugger is active!
[2022-12-02 08:54:12,055] WARNING in _internal:  * Debugger is active!
[2022-12-02 08:54:33,391] WARNING in _internal:  * Debugger is active!
[2022-12-02 08:57:59,136] WARNING in _internal:  * Debugger is active!
[2022-12-02 08:58:43,018] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:07:24,875] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:08:19,977] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:10:43,200] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:13:12,832] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:15:05,285] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:15:46,231] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:19:14,982] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:22:49,614] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:28:11,749] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:28:46,528] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:42:17,404] WARNING in _internal:  * Debugger is active!
[2022-12-02 09:52:44,202] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:00:31,705] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:02:07,626] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:08:27,268] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:08:30,734] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:09:52,978] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:25:34,955] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:26:48,075] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:27:04,434] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:27:15,165] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:28:30,399] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:28:49,975] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:29:37,481] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:29:44,643] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:31:14,112] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:31:25,727] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:32:07,217] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:32:39,972] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:34:50,127] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:36:06,511] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:42:30,567] ERROR in app: Exception on /profile/ [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/grey/WebProject/team_2web/blueprint/profile_blueprint.py", line 76, in index
    return redirect(url_for("login"))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'User.login' instead?
[2022-12-02 10:42:47,399] ERROR in app: Exception on /profile/ [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/grey/WebProject/team_2web/blueprint/profile_blueprint.py", line 76, in index
    return redirect(url_for("login"))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'User.login' instead?
[2022-12-02 10:39:32,332] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:45:28,733] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:49:55,061] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:53:37,747] WARNING in _internal:  * Debugger is active!
[2022-12-02 10:55:06,159] WARNING in _internal:  * Debugger is active!
[2022-12-02 11:11:33,582] WARNING in _internal:  * Debugger is active!
